### ISSUE TITLE
[BUG]  RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by gaceladri** [NVIDIA-Merlin/Transformers4Rec#320]
### Bug description

```
~/anaconda3/envs/nvt/lib/python3.8/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1288             self.control = self.callback_handler.on_epoch_begin(args, self.state, self.control)
   1289 
-> 1290             for step, inputs in enumerate(epoch_iterator):
   1291 
   1292                 # Skip past any already trained steps if resuming training

~/anaconda3/envs/nvt/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    433         if self._sampler_iter is None:
    434             self._reset()
--> 435         data = self._next_data()
    436         self._num_yielded += 1
    437         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/nvt/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    473     def _next_data(self):
    474         index = self._next_index()  # may raise StopIteration
--> 475         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    476         if self._pin_memory:
    477             data = _utils.pin_memory.pin_memory(data)

~/anaconda3/envs/nvt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     26             for _ in possibly_batched_index:
     27                 try:
---> 28                     data.append(next(self.dataset_iter))
     29                 except StopIteration:
     30                     break

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in __next__(self)
    297 
    298     def __next__(self):
--> 299         return self._get_next_batch()
    300 
    301     def _fetch_chunk(self):

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in _get_next_batch(self)
    324         # get the first chunks
    325         if self._batch_itr is None:
--> 326             self._fetch_chunk()
    327 
    328         # try to iterate through existing batches

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in _fetch_chunk(self)
    303         if isinstance(chunks, Exception):
    304             self.stop()
--> 305             raise chunks
    306         self._batch_itr = iter(chunks)
    307 

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in load_chunks(self, dev)
    138             if self.dataloader.device != "cpu":
    139                 with self.dataloader._get_device_ctx(dev):
--> 140                     self.chunk_logic(itr)
    141             else:
    142                 self.chunk_logic(itr)

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in chunk_logic(self, itr)
    121 
    122             if len(chunks) > 0:
--> 123                 chunks = self.dataloader.make_tensors(chunks, self.dataloader._use_nnz)
    124                 # put returns True if buffer is stopped before
    125                 # packet can be put in queue. Keeps us from

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in make_tensors(self, gdf, use_nnz)
    430 
    431                 batches[n].append(c)
--> 432         return [self._handle_tensors(*batch) for batch in batches]
    433 
    434     def _get_segment_lengths(self, num_samples):

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in <listcomp>(.0)
    430 
    431                 batches[n].append(c)
--> 432         return [self._handle_tensors(*batch) for batch in batches]
    433 
    434     def _get_segment_lengths(self, num_samples):

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in _handle_tensors(self, cats, conts, labels)
    560                         f"Did not convert {column_name} to sparse due to missing sparse_max entry"
    561                     )
--> 562                 X[column_name] = self._to_sparse_tensor(X[column_name], column_name)
    563 
    564         # TODO: use dict for labels as well?

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/backend.py in _to_sparse_tensor(self, values_offset, column_name)
    457                 + f"largest sequence in this batch have {max_seq_len} length"
    458             )
--> 459         return self._build_sparse_tensor(values, offsets, diff_offsets, num_rows, seq_limit)
    460 
    461     def _to_tensor(self, gdf, dtype=None):

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/torch.py in _build_sparse_tensor(self, values, offsets, diff_offsets, num_rows, seq_limit)
    176 
    177     def _build_sparse_tensor(self, values, offsets, diff_offsets, num_rows, seq_limit):
--> 178         indices = self._get_indices(offsets, diff_offsets)
    179         return self._get_sparse_tensor(values, indices, num_rows, seq_limit)
    180 

~/anaconda3/envs/nvt/lib/python3.8/site-packages/nvtabular/loader/torch.py in _get_indices(self, offsets, diff_offsets)
    161     def _get_indices(self, offsets, diff_offsets):
    162         row_ids = torch.arange(len(offsets) - 1, device=self.device)
--> 163         row_ids_repeated = torch.repeat_interleave(row_ids, diff_offsets)
    164         row_offset_repeated = torch.repeat_interleave(offsets[:-1], diff_offsets)
    165         col_ids = torch.arange(len(row_offset_repeated), device=self.device) - row_offset_repeated

RuntimeError: CUDA error: invalid device ordinal
```

### Steps/Code to reproduce bug

```
import os
import glob

import torch
import transformers4rec.torch as tr

from transformers4rec.torch.ranking_metric import NDCGAt, RecallAt
from merlin_standard_lib import Schema

# Define schema object to pass it to the TabularSequenceFeatures class
SCHEMA_PATH = './schema/schema.pbtxt'
schema = Schema().from_proto_text(SCHEMA_PATH)
schema = schema.select_by_name(['product_url_hash_list', "nb_interactions-list", "product_sku_hash_list", "ts-list"])

sequence_length = 30
inputs = tr.TabularSequenceFeatures.from_schema(
        schema,
        max_sequence_length=30,
        continuous_projection=64,
        d_output=64,
        masking="mlm",
)
# Define XLNetConfig class and set default parameters for HF XLNet config  
transformer_config = tr.XLNetConfig.build(
    d_model=64, n_head=4, n_layer=2, total_seq_length=30
)
# Define the model block including: inputs, masking, projection and transformer block.
body = tr.SequentialBlock(
    inputs, tr.MLPBlock([64]), tr.TransformerBlock(transformer_config, masking=inputs.masking)
)

# Defines the evaluation top-N metrics and the cut-offs
metrics = [NDCGAt(top_ks=[20, 40], labels_onehot=True),  
           RecallAt(top_ks=[20, 40], labels_onehot=True)]

# Define a head related to next item prediction task 
head = tr.Head(
    body,
    tr.NextItemPredictionTask(weight_tying=True, hf_format=True, 
                              metrics=metrics),
    inputs=inputs,
)

# Get the end-to-end Model class 
model = tr.Model(head)

from transformers4rec.config.trainer import T4RecTrainingArguments
from transformers4rec.torch import Trainer

# Set hyperparameters for training
train_args = T4RecTrainingArguments(
    data_loader_engine="nvtabular",
    dataloader_drop_last=True,
    report_to=[],
    gradient_accumulation_steps=1,
    per_device_train_batch_size=12,
    per_device_eval_batch_size=12,
    output_dir="./tmp",
    learning_rate=0.0005,
    lr_scheduler_type="cosine",
    learning_rate_num_cosine_cycles_by_epoch=1.5,
    num_train_epochs=5,
    max_sequence_length=30,
    no_cuda=False,
)

# Instantiate the T4Rec Trainer, which manages training and evaluation for the PyTorch API
trainer = Trainer(
    model=model,
    args=train_args,
    schema=schema,
    compute_metrics=True,
)

OUTPUT_DIR = "../data/processed/time_splits/"
from transformers4rec.torch.utils.examples_utils import fit_and_evaluate
%%time
start_time_window_index = 1
final_time_window_index = 7
#Iterating over days of one week
for time_index in range(start_time_window_index, final_time_window_index):
    # Set data 
    time_index_train = time_index
    time_index_eval = time_index + 1
    train_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_train}/train.parquet"))
    eval_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_eval}/valid.parquet"))
    print(train_paths)
    
    # Train on day related to time_index 
    print('*'*20)
    print("Launch training for day %s are:" %time_index)
    print('*'*20 + '\n')
    trainer.train_dataset_or_path = train_paths
    trainer.reset_lr_scheduler()
    trainer.train()
    trainer.state.global_step +=1
    print('finished')
    
    # Evaluate on the following day
    trainer.eval_dataset_or_path = eval_paths
    train_metrics = trainer.evaluate(metric_key_prefix='eval')
    print('*'*20)
    print("Eval results for day %s are:\t" %time_index_eval)
    print('\n' + '*'*20 + '\n')
    for key in sorted(train_metrics.keys()):
        print(" %s = %s" % (key, str(train_metrics[key]))) 
    wipe_memory()
```

### Environment details
- Transformers4Rec version: 0.1.2
- Platform: linux ubuntu 20
- Python version: 3.8.12
- Huggingface Transformers version: 4.12.3
- PyTorch version (GPU?): 1.7.1

**Comment by rnyak** [comment]
@gaceladri are you using Merlin containers? if yes which version? 21.09 or 21.11? can you please copy here the print outs of `nvidia-smi` and `nvcc --version`?

**Comment by gaceladri** [comment]
No, installed by conda
The yaml of the enviroment:

```
name: nvt_test
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nvtabular=0.7
  - python>=3.7
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
  - ipython=7.27.0
  - notebook=6.4.4
  - ipykernel
  - transformers4rec
  - pip:
    - torchmetrics==0.6.0
```

**Comment by gaceladri** [comment]
pip freeze >> 
```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1615404881292/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1636021380558/work
async-generator==1.10
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
betterproto @ file:///home/conda/feedstock_root/build_artifacts/betterproto_1607719473855/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1634387997587/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1636012188166/work
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1633010882559/work
certifi==2021.10.8
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1636046063618/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1635814844635/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1635822600067/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1631273254894/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1636040645081/work
cudf==21.8.3
cupy @ file:///home/conda/feedstock_root/build_artifacts/cupy_1601559444486/work
cytoolz==0.11.2
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1627079881899/work
dask-cudf==21.8.3
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1636043259437/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1627088817165/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1602701739019/work/dist/entrypoints-0.3-py2.py3-none-any.whl
fastavro @ file:///home/conda/feedstock_root/build_artifacts/fastavro_1635844669431/work
fastrlock==0.8
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1635559102399/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1636203345794/work
googleapis-common-protos @ file:///home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1636053077840/work
grpclib @ file:///home/conda/feedstock_root/build_artifacts/grpclib_1630026839588/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1633502707516/work
HeapDict==1.0.1
hpack==4.0.0
huggingface-hub @ file:///home/conda/feedstock_root/build_artifacts/huggingface_hub_1636414419863/work
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///tmp/build/80754af9/idna_1622654382723/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1636431522037/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1635615662634/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1634726336619/work/dist/ipykernel-6.4.2-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1630172518090/work
ipython-genutils==0.2.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1635824018136/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1633656206378/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1633637554808/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1636165360877/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1633454794268/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1635407123786/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
llvmlite==0.37.0
locket==0.2.1
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1635833572614/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1635844675081/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1635831468812/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1636019077110/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1636373223849/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1632535919595/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1631733685426/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1633674384332/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1622014599281/work
nvtabular @ file:///home/ben/miniconda3/conda-bld/nvtabular_1636144214087/work
nvtx @ file:///home/conda/feedstock_root/build_artifacts/nvtx_1612462197291/work
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1635539860161/work
pandas==1.2.5
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1617910651905/work
pexpect==4.8.0
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602535658641/work
Pillow==8.4.0
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1635538335951/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1636045889479/work
protobuf==3.18.1
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1635822683783/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyarrow==4.0.1
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
pynvml==11.0.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1633192417276/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1635267989520/work
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1636052595786/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1635862404924/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1633452062248/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1636139793187/work
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1635877406326/work
regex @ file:///home/conda/feedstock_root/build_artifacts/regex_1635966117719/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1626393743643/work
rmm==21.8.2
sacremoses @ file:///home/conda/feedstock_root/build_artifacts/sacremoses_1636276757411/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
stringcase==1.2.0
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tensorflow-metadata @ file:///home/conda/feedstock_root/build_artifacts/tensorflow-metadata_1627562264394/work/tensorflow_metadata-1.2.0-py3-none-any.whl
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1636052221351/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
tokenizers @ file:///home/conda/feedstock_root/build_artifacts/tokenizers_1632285665555/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1636177962100/work
torch==1.7.1
torchaudio==0.7.0a0+a853dff
torchmetrics==0.6.0
torchvision @ file:///tmp/build/80754af9/torchvision_1622214673755/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1635819587273/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1632160078689/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1635260543454/work
transformers @ file:///home/conda/feedstock_root/build_artifacts/transformers_1636006864908/work
transformers4rec @ file:///home/ben/miniconda3/conda-bld/transformers4rec_1636135581458/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1632313171031/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1632350318291/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
zict==2.0.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work

```

**Comment by gaceladri** [comment]
NVIDIA-SMI 470.74  Driver Version: 470.74  CUDA Version: 11.4 (but in the environment is installed cudatoolkit=11.0)
Executed [fashion mnist ](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html)on cuda without problems in that environment

**Comment by rnyak** [comment]
@benfred for viz.

**Comment by rnyak** [comment]
@gaceladri can you upgrade the pytorch to 1.9 or 1.10.0 and try again?

**Comment by gaceladri** [comment]
I think that this is going to be the issue! I had forgotten that with the NVIDIA 3090 you can not go with a cuda driver lower than 11.3! I am installing the new version of pytorch with cuda 11.3 and I will let you know! thanks for the support! By the way, as I am playing with notebooks I think that I cannot do that with docker right? Thanks!

**Comment by rnyak** [comment]
> I think that this is going to be the issue! I had forgotten that with the NVIDIA 3090 you can not go with a cuda driver lower than 11.3! I am installing the new version of pytorch with cuda 11.3 and I will let you know! thanks for the support! By the way, as I am playing with notebooks I think that I cannot do that with docker right? Thanks!

also please us   `torchmetrics==0.3.2` as we recommend in  https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/requirements/pytorch.txt 
Please see all of our our requirements files: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/requirements

And you can easily use notebooks with containers, if that's your question? you only need to pull the container, launch it and then launch the jupyter lab with `jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''`

see the instructions here: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples

**Comment by gaceladri** [comment]
I am going to try installing docker and pulling that image as I am getting conflicts with the cuda version and cupy
```
Encountered problems while solving.
Problem: nothing provides __glibc >=2.17 needed by cupy-9.3.0-py37h4838bcf_0
```
when trying to install from that yml environment: 
```
name: nvt_torch
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nvtabular
  - pip
  - python>=3.7
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchaudio
  - ipython=7.27.0
  - notebook=6.4.4
  - ipykernel
  - transformers4rec
  - pip:
    - torchmetrics==0.3.2
```

**Comment by gaceladri** [comment]
It worked like a charm with the docker version that you pointed! thank you so much for the patience and the support! thanks!

**Comment by TusakaRin** [comment]
@gaceladri Could you please tell which docker container you pull? I've tried this one, https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch-training. However, there's no directory called transformers4rec at / . And because of the pytorch version installed in the docker, I can not run examples in the docker on my 3090. A user warning poped up saying that the pytorch version doesn't support capability sm_82. I've also tried to install a higher version pytorch, but cuda error occurred when I start training.
